sudo: false

language: node_js

node_js: stable

env:
  global:
  # for screen
  - DISPLAY=:99.0
  - TRAVIS=1
  - JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/../firefox/firefox

before_script:  # turn off screen
  - sh -e /etc/init.d/xvfb start
  - sleep 2 # give xvfb some time to start

  - npm i -g get-firefox
  - cd ..
  - get-firefox -ceb unbranded-release
  - cd $TRAVIS_BUILD_DIR

notifications:
  email: false
